Repository 3ree4our/ddip, pull requests merged in 2024-09, with the labels that each got.

#4 [#2] CI/CD 파이프라인 구축
  .dockerignore
  Dockerfile
  Jenkinsfile
  check-and-restart.sh
  deploy.sh
  set-up-docker.sh
Labels: deployment

#5 [#3] 배포 서버에 SSL/TLS 인증 적용
  Dockerfile
  Jenkinsfile
  check-and-restart.sh
  deploy.sh
  src/main/resources/application.yml
Labels: deployment

#7 [#6] MariaDB에 대한 AWS RDS 서비스 적용
  deploy.sh
  src/main/resources/application.yml
Labels: configuration, deployment

#11 [#10 Jenkins Credentials 초기화가 실패하는 문제 해결
  src/main/resources/application.yml
Labels: bug

#13 [#12] 전체 프로젝트의 로깅 프로세스 추가
  src/main/java/org/threefour/ddip/aop/LoggingAspect.java
  src/main/java/org/threefour/ddip/configuration/InterceptorConfig.java
  src/main/java/org/threefour/ddip/interception/LoggingInterceptor.java
  src/main/java/org/threefour/ddip/util/LogConstant.java
  src/main/java/org/threefour/ddip/util/PerformanceMeasurer.java
  src/main/resources/logback-spring.xml
Labels: enhancement, configuration

#16 [#14] 엔티티의 생성, 수정 시간을 관리하는 BaseEntity 추가
  src/main/java/org/threefour/ddip/audit/BaseEntity.java
  src/main/java/org/threefour/ddip/configuration/AuditConfig.java
Labels: enhancement, configuration

#17 [#15] 공통 예외 처리를 위한 Exception Handler 추가
  src/main/java/org/threefour/ddip/exception/ErrorResponse.java
  src/main/java/org/threefour/ddip/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/exception/GlobalExceptionHandler.java
Labels: enhancement

#18 feat(address): 주소 등록
  src/main/java/org/threefour/ddip/address/Repository/AddressRepository.java
  src/main/java/org/threefour/ddip/address/controller/AddressController.java
  src/main/java/org/threefour/ddip/address/domain/Address.java
  src/main/java/org/threefour/ddip/address/service/AddressService.java
  src/main/java/org/threefour/ddip/address/service/AddressServiceImpl.java
  src/main/java/org/threefour/ddip/member/controller/MemberController.java
  src/main/java/org/threefour/ddip/member/domain/Member.java
  src/main/java/org/threefour/ddip/member/repository/MemberRepository.java
  src/main/java/org/threefour/ddip/member/service/MemberService.java
  src/main/java/org/threefour/ddip/member/service/MemberServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/templates/member/member-address.html
  src/main/resources/templates/member/registration.html
  src/main/resources/templates/member/result.html
  src/main/resources/templates/product/registration.html
  src/main/resources/templates/school/registration.html
Labels: enhancement

#20 [#19] CI/CD 파이프라인에 네이버 API 환경변수 추가
  Jenkinsfile
  deploy.sh
Labels: configuration

#21 [#19] 젠킨스파일의 누락된 쉼표 추가
  Jenkinsfile
Labels: bug, configuration

#23 [#22] 자동 DDL 설정을 create로 변경
  src/main/resources/application.yml
Labels: bug, configuration, deployment

#25 [#24] 서버 애플리케이션 실행 시 JSONException 클래스를 찾지 못하는 문제 해결
  build.gradle
  src/main/java/org/threefour/ddip/address/controller/AddressController.java
  src/main/java/org/threefour/ddip/address/service/AddressService.java
  src/main/java/org/threefour/ddip/address/service/AddressServiceImpl.java
Labels: bug

#34 [#32] AWS S3, STS 의존성 추가
  build.gradle
Labels: configuration

#36 [#35] 서버에 S3 Access key 값이 전달되지 않는 문제 해결
  Jenkinsfile
Labels: bug, deployment

#39 [#38] 일반적인 엔티티의 컬럼을 공유하는 BaseGeneralEntity 추가
  src/main/java/org/threefour/ddip/audit/BaseGeneraltEntity.java
Labels: configuration

#40 [#37] 대상 도메인의 이미지 저장 기능 추가
  src/main/java/org/threefour/ddip/image/domain/Image.java
  src/main/java/org/threefour/ddip/image/domain/TargetType.java
  src/main/java/org/threefour/ddip/image/exception/S3UploadFailedException.java
  src/main/java/org/threefour/ddip/image/repository/ImageRepository.java
  src/main/java/org/threefour/ddip/image/service/ImageService.java
  src/main/java/org/threefour/ddip/image/service/ImageServiceImpl.java
Labels: enhancement

#42 [#41] 대상 도메인의 이미지 목록 조회 기능 추가
  src/main/java/org/threefour/ddip/audit/BaseGeneralEntity.java
  src/main/java/org/threefour/ddip/image/domain/Image.java
  src/main/java/org/threefour/ddip/image/service/ImageService.java
  src/main/java/org/threefour/ddip/image/service/ImageServiceImpl.java
  src/main/java/org/threefour/ddip/util/EntityConstant.java
Labels: enhancement

#43 [#37] 이미지 저장 요청 기능 구현
  src/main/java/org/threefour/ddip/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/exception/InvalidTargetTypeException.java
  src/main/java/org/threefour/ddip/exception/InvalidValueException.java
  src/main/java/org/threefour/ddip/image/controller/ImageController.java
  src/main/java/org/threefour/ddip/image/domain/AddImagesRequest.java
  src/main/java/org/threefour/ddip/util/FormatConverter.java
Labels: enhancement

#45 [#44] 이미지 삭제 기능 추가
  src/main/java/org/threefour/ddip/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/exception/ParsingLongException.java
  src/main/java/org/threefour/ddip/image/controller/ImageController.java
  src/main/java/org/threefour/ddip/image/domain/GetImageResponse.java
  src/main/java/org/threefour/ddip/image/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/image/exception/ImageNotFoundException.java
  src/main/java/org/threefour/ddip/image/repository/ImageRepository.java
  src/main/java/org/threefour/ddip/image/service/ImageService.java
  src/main/java/org/threefour/ddip/image/service/ImageServiceImpl.java
  src/main/java/org/threefour/ddip/util/FormatConverter.java
Labels: enhancement

#46 [#44] Image 클래스와 BaseGeneralEntity 클래스 업데이트
  src/main/java/org/threefour/ddip/audit/BaseGeneralEntity.java
  src/main/java/org/threefour/ddip/image/domain/Image.java
Labels: enhancement

#48 [#47] CI/CD 파이프라인에 docker-compose 적용
  Dockerfile
  Jenkinsfile
  build.gradle
  check-and-restart.sh
  deploy.sh
  docker-compose.yml
  set-up-docker.sh
Labels: configuration, deployment

#49 [#47] 애플리케이션 설정 변경
  src/main/resources/application.yml
Labels: configuration

#51 [#50] Jenkins 파이프라인에서 EOF 명령어를 해석하지 못하는 문제 해결
  Jenkinsfile
Labels: bug, deployment

#52 [#50] 중복된 파이프라인 제거
  Jenkinsfile
Labels: bug, deployment

#54 [#53] 데이터베이스 분산 처리를 위한 라우팅 설정
  Jenkinsfile
  docker-compose.yml
  src/main/java/org/threefour/ddip/configuration/DataSourceConfig.java
  src/main/java/org/threefour/ddip/configuration/TransactionConfig.java
  src/main/java/org/threefour/ddip/datasource/CustomRoutingDataSource.java
  src/main/java/org/threefour/ddip/datasource/DatabaseType.java
  src/main/resources/application.yml
Labels: configuration, deployment

#55 [#53] mariadb-container의 이름과 비밀번호 상수를 slave로 변경
  docker-compose.yml
Labels: bug, configuration, deployment

#57 [#56] 배포 서버 애플리케이션에 PROJECT_NAME 환경변수가 전달되지 않는 문제 해결
  docker-compose.yml
Labels: bug, deployment

#58 [#53] Hibernate의 자동 DDL 설정을 create로 변경
  src/main/resources/application.yml
Labels: configuration

#63 [#59] 카테고리 조회 기능 추가
  src/main/java/org/threefour/ddip/product/category/controller/CategoryController.java
  src/main/java/org/threefour/ddip/product/category/domain/Category.java
  src/main/java/org/threefour/ddip/product/category/domain/CategoryName.java
  src/main/java/org/threefour/ddip/product/category/domain/GetCategoryResponse.java
  src/main/java/org/threefour/ddip/product/category/exception/CategoryNotFoundException.java
  src/main/java/org/threefour/ddip/product/category/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/product/category/repository/CategoryRepository.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryService.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryServiceImpl.java
  src/main/java/org/threefour/ddip/util/FormatConverter.java
Labels: enhancement

#64 [#60] 카테고리 등록 기능 추가
  src/main/java/org/threefour/ddip/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/exception/ParsingShortException.java
  src/main/java/org/threefour/ddip/product/category/controller/CategoryController.java
  src/main/java/org/threefour/ddip/product/category/domain/RegisterCategoryRequest.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryService.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryServiceImpl.java
Labels: enhancement

#65 [#61] 카테고리 목록 조회 기능 추가
  src/main/java/org/threefour/ddip/product/category/controller/CategoryController.java
  src/main/java/org/threefour/ddip/product/category/domain/GetCategoriesResponse.java
  src/main/java/org/threefour/ddip/product/category/repository/CategoryRepository.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryService.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryServiceImpl.java
  src/main/java/org/threefour/ddip/util/FormatValidator.java
Labels: enhancement

#66 [#62] 카테고리 삭제 기능 추가
  src/main/java/org/threefour/ddip/product/category/controller/CategoryController.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryService.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryServiceImpl.java
  src/main/java/org/threefour/ddip/util/RegularExpressionConstant.java
Labels: enhancement

#67 [#62] 카테고리 엔티티에 delete 메서드 추가
  src/main/java/org/threefour/ddip/product/category/domain/Category.java
Labels: enhancement

#69 [#68] 상품 등록 기능 추가
  src/main/java/org/threefour/ddip/exception/NoValueException.java
  src/main/java/org/threefour/ddip/image/domain/Image.java
  src/main/java/org/threefour/ddip/product/category/domain/Category.java
  src/main/java/org/threefour/ddip/product/category/domain/ConnectCategoryRequest.java
  src/main/java/org/threefour/ddip/product/category/domain/ProductCategory.java
  src/main/java/org/threefour/ddip/product/category/domain/ProductCategoryId.java
  src/main/java/org/threefour/ddip/product/category/repository/ProductCategoryRepository.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryService.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryServiceImpl.java
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
  src/main/java/org/threefour/ddip/product/domain/Price.java
  src/main/java/org/threefour/ddip/product/domain/Product.java
  src/main/java/org/threefour/ddip/product/domain/RegisterProductRequest.java
  src/main/java/org/threefour/ddip/product/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/product/exception/InvalidPriceException.java
  src/main/java/org/threefour/ddip/product/exception/PriceNoValueException.java
  src/main/java/org/threefour/ddip/product/repository/ProductRepository.java
  src/main/java/org/threefour/ddip/product/service/ProductService.java
  src/main/java/org/threefour/ddip/product/service/ProductServiceImpl.java
  src/main/java/org/threefour/ddip/util/FormatValidator.java
  src/main/resources/templates/product/registration.html
Labels: enhancement

#70 [#68] String에서 int 타입으로의 변환 메서드 추가
  src/main/java/org/threefour/ddip/util/FormatConverter.java
Labels: enhancement

#71 [#68] String에서 int 타입으로의 변환 시 커스텀 예외 처리 추가
  src/main/java/org/threefour/ddip/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/exception/ParsingIntegerException.java
Labels: enhancement

#72 [#68] registration.html 페이지의 카테고리 조회 요청 URL 변경
  src/main/resources/application.yml
  src/main/resources/templates/product/registration.html
Labels: enhancement

#75 [#74] Jenkins 파이프라인에서 이미 존재하는 mariadb-container와 redis-container를 재설치하지 않도록 설정
  Jenkinsfile
Labels: configuration, deployment

#76 [#74] 애플리케이션 컨테이너 이름을 환경변수화
  Jenkinsfile
Labels: configuration, deployment

#78 [#77] 가격정보 등록 기능 추가
  src/main/java/org/threefour/ddip/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/exception/ParsingFloatException.java
  src/main/java/org/threefour/ddip/exception/ParsingTimestampException.java
  src/main/java/org/threefour/ddip/product/domain/AutoDiscountRequest.java
  src/main/java/org/threefour/ddip/product/domain/RegisterProductRequest.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/MinPrice.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/NextDiscountedAt.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/PriceDiscountPeriod.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/PriceDiscountRate.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/PriceInformation.java
  src/main/java/org/threefour/ddip/product/priceinformation/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/product/priceinformation/exception/InvalidNextDiscountedAtException.java
  src/main/java/org/threefour/ddip/product/priceinformation/exception/InvalidPriceDiscountPeriodException.java
  src/main/java/org/threefour/ddip/product/priceinformation/exception/InvalidPriceDiscountRateException.java
  src/main/java/org/threefour/ddip/product/priceinformation/exception/NextDiscountedAtNoValueException.java
  src/main/java/org/threefour/ddip/product/priceinformation/exception/PriceDiscountPeriodNoValueException.java
  src/main/java/org/threefour/ddip/product/priceinformation/exception/PriceDiscountRateNoValueException.java
  src/main/java/org/threefour/ddip/product/priceinformation/repository/PriceInformationRepository.java
  src/main/java/org/threefour/ddip/product/priceinformation/service/PriceInformationService.java
  src/main/java/org/threefour/ddip/product/priceinformation/service/PriceInformationServiceImpl.java
  src/main/java/org/threefour/ddip/product/service/ProductServiceImpl.java
  src/main/java/org/threefour/ddip/util/EntityConstant.java
  src/main/java/org/threefour/ddip/util/FormatConverter.java
  src/main/java/org/threefour/ddip/util/FormatValidator.java
Labels: enhancement

#80 [#79] 상품 조회 기능 추가
  src/main/java/org/threefour/ddip/product/category/domain/GetCategoriesResponse.java
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
  src/main/java/org/threefour/ddip/product/domain/GetProductResponse.java
  src/main/java/org/threefour/ddip/product/domain/Product.java
  src/main/java/org/threefour/ddip/product/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/product/exception/ProductNotFoundException.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/GetPriceInformationListResponse.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/GetPriceInformationResponse.java
  src/main/java/org/threefour/ddip/product/service/ProductService.java
  src/main/java/org/threefour/ddip/product/service/ProductServiceImpl.java
  src/main/resources/templates/product/details.html
Labels: enhancement, view

#82 [#81] 카테고리 도메인의 요청 URL 변경
  src/main/java/org/threefour/ddip/product/category/controller/CategoryController.java
  src/main/resources/templates/product/details.html
  src/main/resources/templates/product/registration.html
Labels: enhancement

#85 [#83] 페이지네이션 상수 정보를 담고 있는 유틸리티 클래스 추가
  src/main/java/org/threefour/ddip/util/PaginationConstant.java
Labels: enhancement

#86 [#83] ProductController의 PaginationConstant에 대한 importing 수정
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
Labels: configuration

#87 [#83] 상품 목록 조회 페이지 추가
  src/main/resources/templates/product/list.html
Labels: enhancement, view

#88 [#73] jdbc 설정의 unicode를 사용하지 않도록 변경
  src/main/resources/application.yml
Labels: bug, configuration, deployment

#90 [#89] 상품 수정 기능 추가
  src/main/java/org/threefour/ddip/audit/BaseGeneralEntity.java
  src/main/java/org/threefour/ddip/image/controller/ImageController.java
  src/main/java/org/threefour/ddip/image/domain/AddImagesRequest.java
  src/main/java/org/threefour/ddip/image/domain/Image.java
  src/main/java/org/threefour/ddip/image/repository/ImageRepository.java
  src/main/java/org/threefour/ddip/image/service/ImageService.java
  src/main/java/org/threefour/ddip/image/service/ImageServiceImpl.java
  src/main/java/org/threefour/ddip/product/category/controller/CategoryController.java
  src/main/java/org/threefour/ddip/product/category/domain/ProductCategory.java
  src/main/java/org/threefour/ddip/product/category/repository/ProductCategoryRepository.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryService.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryServiceImpl.java
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
  src/main/java/org/threefour/ddip/product/domain/Price.java
  src/main/java/org/threefour/ddip/product/domain/Product.java
  src/main/java/org/threefour/ddip/product/domain/UpdateProductRequest.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/MinPrice.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/NextDiscountedAt.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/PriceDiscountPeriod.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/PriceDiscountRate.java
  src/main/java/org/threefour/ddip/product/service/ProductService.java
  src/main/java/org/threefour/ddip/product/service/ProductServiceImpl.java
  src/main/java/org/threefour/ddip/util/FormatValidator.java
  src/main/resources/templates/product/modification.html
  src/main/resources/templates/product/registration.html
Labels: enhancement, view

#92 [#91] 상품 삭제 기능 추가
  src/main/java/org/threefour/ddip/product/category/service/CategoryServiceImpl.java
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
  src/main/java/org/threefour/ddip/product/domain/Product.java
  src/main/java/org/threefour/ddip/product/service/ProductService.java
  src/main/java/org/threefour/ddip/product/service/ProductServiceImpl.java
  src/main/resources/templates/product/details.html
  src/main/resources/templates/product/modification.html
Labels: enhancement, view

#94 [#93] 상품 도메인에 Redis Cache 적용
  build.gradle
  src/main/java/org/threefour/ddip/audit/BaseEntity.java
  src/main/java/org/threefour/ddip/configuration/CacheConfig.java
  src/main/java/org/threefour/ddip/hibernate/HibernateCollectionIdResolver.java
  src/main/java/org/threefour/ddip/hibernate/HibernateCollectionMixIn.java
  src/main/java/org/threefour/ddip/image/service/ImageServiceImpl.java
  src/main/java/org/threefour/ddip/product/category/controller/CategoryController.java
  src/main/java/org/threefour/ddip/product/category/domain/Category.java
  src/main/java/org/threefour/ddip/product/category/domain/ProductCategory.java
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
  src/main/java/org/threefour/ddip/product/domain/GetProductResponse.java
  src/main/java/org/threefour/ddip/product/domain/Price.java
  src/main/java/org/threefour/ddip/product/domain/Product.java
  src/main/java/org/threefour/ddip/product/domain/RegisterProductRequest.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/MinPrice.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/PriceDiscountPeriod.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/PriceDiscountRate.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/PriceInformation.java
  src/main/java/org/threefour/ddip/product/service/ProductService.java
  src/main/java/org/threefour/ddip/product/service/ProductServiceImpl.java
  src/main/java/org/threefour/ddip/util/FormatValidator.java
  src/main/java/org/threefour/ddip/util/RegularExpressionConstant.java
  src/main/resources/templates/product/registration.html
Labels: enhancement, configuration

#98 [#97] 거래 등록 기능 추가
  src/main/java/org/threefour/ddip/deal/controller/DealController.java
  src/main/java/org/threefour/ddip/deal/domain/Deal.java
  src/main/java/org/threefour/ddip/deal/domain/DealAmount.java
  src/main/java/org/threefour/ddip/deal/domain/DealStatus.java
  src/main/java/org/threefour/ddip/deal/domain/InitializeDealRequest.java
  src/main/java/org/threefour/ddip/deal/exception/DealAmountNoValueException.java
  src/main/java/org/threefour/ddip/deal/exception/DealNotFoundException.java
  src/main/java/org/threefour/ddip/deal/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/deal/exception/InvalidDealAmountException.java
  src/main/java/org/threefour/ddip/deal/exception/InvalidWaitingNumberException.java
  src/main/java/org/threefour/ddip/deal/repository/DealRepository.java
  src/main/java/org/threefour/ddip/deal/service/DealService.java
  src/main/java/org/threefour/ddip/deal/service/DealServiceImpl.java
  src/main/java/org/threefour/ddip/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/exception/TokenNoValueException.java
  src/main/java/org/threefour/ddip/member/domain/Member.java
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
  src/main/java/org/threefour/ddip/product/domain/GetProductResponse.java
  src/main/java/org/threefour/ddip/product/domain/GetProductsResponse.java
  src/main/java/org/threefour/ddip/product/domain/PageInformation.java
  src/main/java/org/threefour/ddip/product/domain/Price.java
  src/main/java/org/threefour/ddip/util/PageableGenerator.java
  src/main/resources/deployment/application.yml
  src/main/resources/templates/member/registration.html
  src/main/resources/templates/product/details.html
  src/main/resources/templates/product/list.html
Labels: enhancement, view

#100 [#99] 누락된 애플리케이션 설정 추가
  src/main/resources/application.yml
Labels: bug, configuration

#107 fix(configuration): 테스트 설정 변경 (#106)
  build.gradle
  src/main/resources/application.yml
  src/test/java/org/threefour/ddip/DdipApplicationTests.java
Labels: bug

#108 [#107] MemberServiceImplTest 클래스의 데이터베이스 설정 변경
  src/test/java/org/threefour/ddip/member/service/MemberServiceImplTest.java
Labels: bug

#109 [#106] 테스트 설정 파일에 naver 환경변수 설정
  src/test/resources/application-test.properties
Labels: bug

#110 [#106] 테스트 설정 파일에 JWT와 AWS S3 환경변수 설정
  src/test/resources/application-test.properties
Labels: bug

#111 [#106] H2 데이터베이스의 환경설정을 runtimeOnly에서 implementation으로 변경
  build.gradle
Labels: bug

#112 [#106] DataSourceConfig 클래스 활성화
  src/main/java/org/threefour/ddip/configuration/DataSourceConfig.java
Labels: bug

#113 [#106] MemberServiceImplTest 클래스 삭제
  src/test/java/org/threefour/ddip/member/service/MemberServiceImplTest.java
Labels: bug

#115 [#114] 회원 도메인에 회원 인증/인가 연동
  src/main/java/org/threefour/ddip/deal/controller/DealController.java
  src/main/java/org/threefour/ddip/deal/domain/InitializeDealRequest.java
  src/main/java/org/threefour/ddip/deal/exception/DealsAlreadyExistException.java
  src/main/java/org/threefour/ddip/deal/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/deal/exception/IdenticalSellerException.java
  src/main/java/org/threefour/ddip/deal/service/DealService.java
  src/main/java/org/threefour/ddip/deal/service/DealServiceImpl.java
  src/main/java/org/threefour/ddip/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
  src/main/java/org/threefour/ddip/product/repository/ProductRepository.java
  src/main/java/org/threefour/ddip/product/service/ProductService.java
  src/main/java/org/threefour/ddip/product/service/ProductServiceImpl.java
  src/main/java/org/threefour/ddip/util/AuthenticationValidator.java
  src/main/java/org/threefour/ddip/util/FormatValidator.java
  src/main/resources/templates/product/details.html
  src/main/resources/templates/product/list.html
  src/main/resources/templates/product/registration.html
Labels: enhancement

#119 [#114] 충돌 해결 과정에서 누락된 변경사항 업데이트
  src/main/java/org/threefour/ddip/authentication/AuthenticationController.java
  src/main/java/org/threefour/ddip/deal/repository/DealRepository.java
  src/main/java/org/threefour/ddip/product/category/repository/ProductCategoryRepository.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryService.java
  src/main/java/org/threefour/ddip/product/category/service/CategoryServiceImpl.java
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
  src/main/java/org/threefour/ddip/product/service/ProductServiceImpl.java
  src/main/java/org/threefour/ddip/util/LogConstant.java
  src/main/resources/templates/product/details.html
  src/main/resources/templates/product/modification.html
  src/main/resources/templates/product/registration.html
Labels: enhancement

#121 [#118] 배포 서버에서 메인 페이지 로드 시 발생하는 TemplateInputException 해결
  src/main/resources/templates/index.html
Labels: bug, deployment, view

#122 [#120] 상품과 카테고리 엔티티에 식별 관계 매핑된 상품 카테고리 엔티티가 물리적으로 삭제되지 않는 문제 해결
  src/main/java/org/threefour/ddip/product/category/service/CategoryServiceImpl.java
Labels: bug

#124 [#123] 이미지 도메인에 Redis Cache 적용
  src/main/java/org/threefour/ddip/image/controller/ImageController.java
  src/main/java/org/threefour/ddip/image/domain/DesignageRepresentativeImageRequest.java
  src/main/java/org/threefour/ddip/image/domain/Image.java
  src/main/java/org/threefour/ddip/image/repository/ImageRepository.java
  src/main/java/org/threefour/ddip/image/service/ImageService.java
  src/main/java/org/threefour/ddip/image/service/ImageServiceImpl.java
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
  src/main/java/org/threefour/ddip/product/domain/GetProductResponse.java
  src/main/java/org/threefour/ddip/product/domain/Product.java
  src/main/java/org/threefour/ddip/product/domain/UpdateProductRequest.java
  src/main/java/org/threefour/ddip/product/exception/ExceptionMessage.java
  src/main/java/org/threefour/ddip/product/exception/UpdateFormNoValueException.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/GetPriceInformationListResponse.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/PriceInformation.java
  src/main/resources/templates/product/modification.html
  src/main/resources/templates/product/registration.html
Labels: enhancement, view

#131 채팅 기능 추가
  .gitignore
  build.gradle
  src/main/java/org/threefour/ddip/chat/controller/ChatAPIController.java
  src/main/java/org/threefour/ddip/chat/controller/ChatMessageController.java
  src/main/java/org/threefour/ddip/chat/controller/ImageLocalController.java
  src/main/java/org/threefour/ddip/chat/controller/WaitingAPIController.java
  src/main/java/org/threefour/ddip/chat/domain/Waiting.java
  src/main/java/org/threefour/ddip/chat/domain/WaitingStatus.java
  src/main/java/org/threefour/ddip/chat/domain/dto/ChatResponseDTO.java
  src/main/java/org/threefour/ddip/chat/domain/dto/ChatroomResponseDTO.java
  src/main/java/org/threefour/ddip/chat/domain/dto/ProductResponseDTO.java
  src/main/java/org/threefour/ddip/chat/domain/dto/WaitingRequestDTO.java
  src/main/java/org/threefour/ddip/chat/domain/dto/WaitingResponseDTO.java
  src/main/java/org/threefour/ddip/chat/repository/ChatRepository.java
  src/main/java/org/threefour/ddip/chat/repository/WaitingRepository.java
  src/main/java/org/threefour/ddip/chat/service/ChatService.java
  src/main/java/org/threefour/ddip/chat/service/ChatServiceImpl.java
  src/main/java/org/threefour/ddip/chat/service/WaitingService.java
  src/main/java/org/threefour/ddip/chat/service/WaitingServiceImpl.java
  src/main/java/org/threefour/ddip/configuration/CacheConfig.java
  src/main/java/org/threefour/ddip/configuration/DataSourceConfig.java
  src/main/java/org/threefour/ddip/configuration/SessionConfig.java
  src/main/java/org/threefour/ddip/deal/controller/DealController.java
  src/main/java/org/threefour/ddip/deal/domain/Deal.java
  src/main/java/org/threefour/ddip/deal/repository/DealRepository.java
  src/main/java/org/threefour/ddip/deal/service/DealService.java
  src/main/java/org/threefour/ddip/deal/service/DealServiceImpl.java
  src/main/java/org/threefour/ddip/image/domain/Image.java
  src/main/java/org/threefour/ddip/image/service/ImageServiceImpl.java
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
  src/main/java/org/threefour/ddip/product/service/ProductServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/deployment/application.yml
  src/main/resources/static/chat/css/alert.css
  src/main/resources/static/chat/css/chat-list.css
  src/main/resources/static/chat/js/alert.js
  src/main/resources/static/chat/js/api.js
  src/main/resources/static/chat/js/chat-list.js
  src/main/resources/static/chat/js/image.js
  src/main/resources/static/fragments/header.html
  src/main/resources/templates/alert/alert.html
  src/main/resources/templates/chat/chat-list.html
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/product/details.html
  src/main/resources/templates/product/registration.html
  src/test/java/org/threefour/ddip/DdipApplicationTests.java
  src/test/resources/application-test.properties
Labels: bug

#134 [#133] 상품 검색 기능 추가, Elasticsearch 적용
  Dockerfile
  Jenkinsfile
  build.gradle
  docker-compose.yml
  src/main/java/org/threefour/ddip/DdipApplication.java
  src/main/java/org/threefour/ddip/chat/controller/ChatMessageController.java
  src/main/java/org/threefour/ddip/configuration/CacheConfig.java
  src/main/java/org/threefour/ddip/configuration/ElasticSearchConfig.java
  src/main/java/org/threefour/ddip/configuration/SessionConfig.java
  src/main/java/org/threefour/ddip/deal/controller/DealController.java
  src/main/java/org/threefour/ddip/image/domain/GetImageResponse.java
  src/main/java/org/threefour/ddip/image/domain/Image.java
  src/main/java/org/threefour/ddip/image/domain/RepresentativeImagesRequest.java
  src/main/java/org/threefour/ddip/image/service/ImageLocalServiceImpl.java
  src/main/java/org/threefour/ddip/image/service/ImageServiceImpl.java
  src/main/java/org/threefour/ddip/member/domain/Member.java
  src/main/java/org/threefour/ddip/member/service/MemberServiceImpl.java
  src/main/java/org/threefour/ddip/product/category/domain/CategoryName.java
  src/main/java/org/threefour/ddip/product/category/domain/GetCategoriesResponse.java
  src/main/java/org/threefour/ddip/product/category/domain/GetCategoryResponse.java
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
  src/main/java/org/threefour/ddip/product/domain/GetProductResponse.java
  src/main/java/org/threefour/ddip/product/domain/GetProductsResponse.java
  src/main/java/org/threefour/ddip/product/domain/PageInformation.java
  src/main/java/org/threefour/ddip/product/domain/Price.java
  src/main/java/org/threefour/ddip/product/domain/Product.java
  src/main/java/org/threefour/ddip/product/elasticsearch/controller/ProductSearchController.java
  src/main/java/org/threefour/ddip/product/elasticsearch/domain/ProductDocument.java
  src/main/java/org/threefour/ddip/product/elasticsearch/domain/ProductNameDto.java
  src/main/java/org/threefour/ddip/product/elasticsearch/domain/SearchProductResponse.java
  src/main/java/org/threefour/ddip/product/elasticsearch/domain/SearchProductsResponse.java
  src/main/java/org/threefour/ddip/product/elasticsearch/repository/ProductComplexSearchRepository.java
  src/main/java/org/threefour/ddip/product/elasticsearch/repository/ProductComplexSearchRepositoryImpl.java
  src/main/java/org/threefour/ddip/product/elasticsearch/repository/ProductSearchRepository.java
  src/main/java/org/threefour/ddip/product/elasticsearch/service/ProductSearchService.java
  src/main/java/org/threefour/ddip/product/elasticsearch/service/ProductSearchServiceImpl.java
  src/main/java/org/threefour/ddip/product/elasticsearch/util/AddressModifier.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/MinPrice.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/NextDiscountedAt.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/PriceDiscountPeriod.java
  src/main/java/org/threefour/ddip/product/priceinformation/domain/PriceDiscountRate.java
  src/main/java/org/threefour/ddip/product/repository/ProductRepositoryImpl.java
  src/main/java/org/threefour/ddip/product/service/ProductServiceImpl.java
  src/main/java/org/threefour/ddip/util/SessionConstant.java
  src/main/resources/application.yml
  src/main/resources/elasticsearch/product-mapping.json
  src/main/resources/elasticsearch/product-setting.json
  src/main/resources/static/fragments/header.html
  src/main/resources/static/js/search.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/product/details.html
  src/main/resources/templates/product/list.html
  src/main/resources/templates/product/modification.html
  src/main/resources/templates/product/registration.html
Labels: enhancement, configuration, deployment, view

#135 (#133) 환경설정 변경사항 추가
  build.gradle
  elasticsearch/Dockerfile
  src/main/java/org/threefour/ddip/DdipApplication.java
  src/main/java/org/threefour/ddip/configuration/DataSourceConfig.java
Labels: configuration, deployment

#137 [#133] Dockerfile의 경로 조정
  Dockerfile
Labels: bug, deployment

#138 [#133] Jenkinsfile의 환경변수 변경
  Jenkinsfile
Labels: bug, deployment

#139 [#133] Jenkins 파이프라인에 배포 서버 IP 환경변수 추가
  Jenkinsfile
  src/main/resources/application.yml
Labels: configuration, deployment

#141 [#133] docker-compose.yml 파일에 환경변수 전달 설정 추가
  docker-compose.yml
Labels: bug, deployment

#144 [#143] lasticsearch의 Heap Space 메모리 부족 문제 해결
  elasticsearch/Dockerfile
  src/main/java/org/threefour/ddip/product/controller/ProductController.java
  src/main/java/org/threefour/ddip/product/elasticsearch/controller/ProductSearchController.java
  src/main/java/org/threefour/ddip/product/elasticsearch/repository/ProductComplexSearchRepository.java
Labels: bug, configuration

#174 [#172] Member 엔티티에서 Addresses 필드를 직렬화하지 못하는 문제 해결
  src/main/java/org/threefour/ddip/address/domain/Address.java
  src/main/java/org/threefour/ddip/member/domain/Member.java
Labels: bug

#175 [#173] fix(product): 상품 상세 페이지에서 로그인 후에도 상품 수정 버튼과 상품 삭제 버튼이 보이지 않는 문제 해결
  src/main/resources/templates/product/details.html
Labels: bug

#178 [#177] README.md 추가
  README.md
Labels: documentation

#180 [#177] README.md 업데이트
  README.md
Labels: documentation
